export const state = {
  limitData: [1, 2],
  type: ['equle', 'over', 'noLessThan', 'less', 'noMoreThan', 'open', 'leftOpen', 'rightOpen', 'close'],
  limitTrigger: [
    {
      color: '#222',
      conditionCode: 'table_5725b0',
      index: 0,
      intervalType: 'equle',
      isTrigger: false,
      left: 300,
      right: 1500,
      time: 10000,
      timeUnit: 'sec',
    },
    {
      color: '#222',
      conditionCode: 'table_5725b0',
      index: 0,
      intervalType: 'over',
      isTrigger: false,
      left: 300,
      right: 1500,
      time: 10000,
      timeUnit: 'sec',
    },
    {
      color: '#222',
      conditionCode: 'table_5725b0',
      index: 0,
      intervalType: 'noLessThan',
      isTrigger: false,
      left: 300,
      right: 1500,
      time: 10000,
      timeUnit: 'sec',
    },
    {
      color: '#222',
      conditionCode: 'table_5725b0',
      index: 0,
      intervalType: 'less',
      isTrigger: false,
      left: 300,
      right: 1500,
      time: 10000,
      timeUnit: 'sec',
    },
    {
      color: '#222',
      conditionCode: 'table_5725b0',
      index: 0,
      intervalType: 'noMoreThan',
      isTrigger: false,
      left: 300,
      right: 1500,
      time: 10000,
      timeUnit: 'sec',
    },
    {
      color: '#222',
      conditionCode: 'table_5725b0',
      index: 0,
      intervalType: 'open',
      isTrigger: false,
      left: 300,
      right: 1500,
      time: 10000,
      timeUnit: 'sec',
    },
    {
      color: '#222',
      conditionCode: 'table_5725b0',
      index: 0,
      intervalType: 'leftOpen',
      isTrigger: false,
      left: 300,
      right: 1500,
      time: 10000,
      timeUnit: 'sec',
    },
    {
      color: '#222',
      conditionCode: 'table_5725b0',
      index: 0,
      intervalType: 'rightOpen',
      isTrigger: false,
      left: 300,
      right: 1500,
      time: 10000,
      timeUnit: 'sec',
    },
    {
      color: '#222',
      conditionCode: 'table_5725b0',
      index: 0,
      intervalType: 'close',
      isTrigger: false,
      left: 300,
      right: 1500,
      time: 10000,
      timeUnit: 'sec',
    },
  ],
  rowItem: [279.8, 784.8],
};
