export const state = {
  app: {
    createTime: 1599553167000,
    createUser: 'dushihua2',
    id: 559,
    modifyTime: 1599553167000,
    modifyUser: 'dushihua2',
    name: 'efgsrfv',
    spaceId: 149,
  },
  canvas: {
    appId: 559,
    backgroundColor: 'black',
    backgroundImg: '',
    createTime: 1599553168000,
    createUser: 'dushihua2',
    height: 1080,
    id: 450,
    modifyTime: 1627027460000,
    modifyUser: 'dushihua2',
    thumbnail: '',
    width: 1922,
    zoomType: 1,
  },
  compCodes: [
    'commonTitle_9157df',
    'commonTitle_3d6872',
    'commonTitle_7a3c3d',
    'group_70b806',
    'commonTitle_25d4b1',
    'commonTitle_b7c173',
    'commonTitle_6f7972',
    'commonTitle_075924',
    'group_d245cd',
    'commonTitle_75db0d',
    'commonTitle_6ffc63',
    'commonTitle_2dbb9f',
    'commonTitle_4f0acb',
    'group_2b918d',
    'commonTitle_358d2d',
    'commonTitle_4836c3',
    'commonTitle_5ad21d',
    'commonTitle_fd092b',
  ],
  compDatas: {
    commonTitle_9157df: {
      alias: '普通文本',
      attr: {
        top: 48,
        left: 122,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_9157df',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14530,
      locked: false,
      title: '普通文本',
    },
    commonTitle_3d6872: {
      alias: '普通文本',
      attr: {
        top: 28,
        left: 102,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_3d6872',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14529,
      locked: false,
      title: '普通文本',
    },
    commonTitle_7a3c3d: {
      alias: '普通文本',
      attr: {
        top: 68,
        left: 142,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_7a3c3d',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14531,
      locked: false,
      title: '普通文本',
    },
    group_70b806: {
      alias: '分组',
      attr: { top: 115, left: 478, width: 1364, angle: 0, scale: [1, 1], height: 697 },
      code: 'group_70b806',
      compCode: 'group',
      version: 'index',
      config: {
        groupItemCode: [
          'commonTitle_075924',
          'commonTitle_b7c173',
          'commonTitle_75db0d',
          'commonTitle_6ffc63',
          'commonTitle_2dbb9f',
          'commonTitle_6f7972',
          'commonTitle_25d4b1',
        ],
      },
      hided: false,
      id: 14550,
      locked: false,
      title: '分组',
    },
    commonTitle_25d4b1: {
      alias: '普通文本',
      attr: {
        top: 235,
        left: 598,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_25d4b1',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
        groupCode: 'group_70b806',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14554,
      locked: false,
      title: '普通文本',
    },
    commonTitle_b7c173: {
      alias: '普通文本',
      attr: {
        top: 135,
        left: 498,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_b7c173',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
        groupCode: 'group_70b806',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14552,
      locked: false,
      title: '普通文本',
    },
    commonTitle_6f7972: {
      alias: '普通文本',
      attr: {
        top: 215,
        left: 578,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_6f7972',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
        groupCode: 'group_70b806',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14553,
      locked: false,
      title: '普通文本',
    },
    commonTitle_075924: {
      alias: '普通文本',
      attr: {
        top: 115,
        left: 478,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_075924',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
        groupCode: 'group_70b806',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14551,
      locked: false,
      title: '普通文本',
    },
    group_d245cd: {
      alias: '分组',
      attr: { top: 700, left: 1502, width: 340, angle: 0, scale: [1, 1], height: 112 },
      code: 'group_d245cd',
      compCode: 'group',
      version: 'index',
      config: {
        groupItemCode: ['commonTitle_75db0d', 'commonTitle_6ffc63', 'commonTitle_2dbb9f'],
        groupCode: 'group_70b806',
      },
      hided: false,
      id: 14546,
      locked: false,
      title: '分组',
    },
    commonTitle_75db0d: {
      alias: '普通文本',
      attr: {
        top: 700,
        left: 1502,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_75db0d',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
        groupCode: 'group_d245cd',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14547,
      locked: false,
      title: '普通文本',
    },
    commonTitle_6ffc63: {
      alias: '普通文本',
      attr: {
        top: 720,
        left: 1522,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_6ffc63',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
        groupCode: 'group_d245cd',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14548,
      locked: false,
      title: '普通文本',
    },
    commonTitle_2dbb9f: {
      alias: '普通文本',
      attr: {
        top: 740,
        left: 1542,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_2dbb9f',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
        groupCode: 'group_d245cd',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14549,
      locked: false,
      title: '普通文本',
    },
    commonTitle_4f0acb: {
      alias: '普通文本',
      attr: {
        top: 228,
        left: 302,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_4f0acb',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14539,
      locked: false,
      title: '普通文本',
    },
    group_2b918d: {
      alias: '分组',
      attr: { top: 248, left: 322, width: 320, angle: 0, scale: [1, 1], height: 92 },
      code: 'group_2b918d',
      compCode: 'group',
      version: 'index',
      config: { groupItemCode: ['commonTitle_358d2d', 'commonTitle_4836c3'] },
      hided: false,
      id: 22673,
      locked: false,
      title: '分组',
    },
    commonTitle_358d2d: {
      alias: '普通文本',
      attr: {
        top: 248,
        left: 322,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_358d2d',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
        groupCode: 'group_2b918d',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14540,
      locked: false,
      title: '普通文本',
    },
    commonTitle_4836c3: {
      alias: '普通文本',
      attr: {
        top: 268,
        left: 342,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_4836c3',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
        groupCode: 'group_2b918d',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14541,
      locked: false,
      title: '普通文本',
    },
    commonTitle_5ad21d: {
      alias: '普通文本',
      attr: {
        top: 288,
        left: 362,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_5ad21d',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14542,
      locked: false,
      title: '普通文本',
    },
    commonTitle_fd092b: {
      alias: '普通文本',
      attr: {
        top: 308,
        left: 382,
        width: 300,
        angle: 0,
        scale: [1, 1],
        lock: false,
        opacity: 1,
        height: 72,
      },
      code: 'commonTitle_fd092b',
      compCode: 'commonTitle',
      version: 'index',
      config: {
        link: { isBlank: false, url: '' },
        style: {
          fontFamily: 'Microsoft Yahei',
          color: '#fff',
          textAlign: 'left',
          letterSpacing: 0,
          fontSize: 28,
          lineHeight: 1,
          textShadow: '',
          fontWeight: 'normal',
          writingMode: 'horizontal-tb',
        },
        title: '默认文本',
      },
      dataConfig: {
        autoRefresh: false,
        dataParams: [],
        dataSourceType: 0,
        fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
        frequency: 1,
        mockData: [{ content: '' }],
        specScript: '',
      },
      hided: false,
      id: 14543,
      locked: false,
      title: '普通文本',
    },
  },
  selectedCompCodes: [],
  copyComps: [],
  originDatas: {
    commonTitle_9157df: [{ content: '' }],
    commonTitle_3d6872: [{ content: '' }],
    commonTitle_7a3c3d: [{ content: '' }],
    commonTitle_25d4b1: [{ content: '' }],
    commonTitle_b7c173: [{ content: '' }],
    commonTitle_6f7972: [{ content: '' }],
    commonTitle_075924: [{ content: '' }],
    commonTitle_75db0d: [{ content: '' }],
    commonTitle_6ffc63: [{ content: '' }],
    commonTitle_2dbb9f: [{ content: '' }],
    commonTitle_4f0acb: [{ content: '' }],
    commonTitle_358d2d: [{ content: '' }],
    commonTitle_4836c3: [{ content: '' }],
    commonTitle_5ad21d: [{ content: '' }],
    commonTitle_fd092b: [{ content: '' }],
  },
  actionAlias: '初始状态',
};
