export const compCode = [
  'group_cb1409',
  'commonTitle_f698a3',
  'commonTitle_ed6e20',
  'commonTitle_675b47',
  'commonTitle_0268f0',
  'commonTitle_67f82d',
  'commonTitle_c13c4a',
  'commonTitle_8a4743',
];
export const compData = {
  commonTitle_f698a3: {
    alias: '普通文本',
    attr: { top: 55, left: 90, width: 300, angle: 0, scale: [1, 1], lock: false, opacity: 1, height: 72 },
    code: 'commonTitle_f698a3',
    compCode: 'commonTitle',
    version: 'index',
    config: {
      link: { isBlank: false, url: '' },
      style: {
        fontFamily: 'FZLTTHJW',
        color: '#fff',
        textAlign: 'left',
        letterSpacing: 0,
        fontSize: 28,
        lineHeight: 1.5,
        textShadow: '',
        fontWeight: 'normal',
        writingMode: 'horizontal-tb',
      },
      title: '默认文本',
      groupCode: 'group_cb1409',
    },
    dataConfig: {
      autoRefresh: false,
      dataParams: [],
      dataSourceType: 0,
      fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
      frequency: 1,
      mockData: [{ content: '' }],
      specScript: '',
    },
    hided: false,
    id: 22869,
    locked: false,
    title: '',
  },
  commonTitle_ed6e20: {
    alias: '普通文本',
    attr: { top: 75, left: 110, width: 300, angle: 0, scale: [1, 1], lock: false, opacity: 1, height: 72 },
    code: 'commonTitle_ed6e20',
    compCode: 'commonTitle',
    version: 'index',
    config: {
      link: { isBlank: false, url: '' },
      style: {
        fontFamily: 'FZLTTHJW',
        color: '#fff',
        textAlign: 'left',
        letterSpacing: 0,
        fontSize: 28,
        lineHeight: 1.5,
        textShadow: '',
        fontWeight: 'normal',
        writingMode: 'horizontal-tb',
      },
      title: '默认文本',
    },
    dataConfig: {
      autoRefresh: false,
      dataParams: [],
      dataSourceType: 0,
      fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
      frequency: 1,
      mockData: [{ content: '' }],
      specScript: '',
    },
    hided: false,
    id: 22870,
    locked: false,
    title: '',
  },
  commonTitle_675b47: {
    alias: '普通文本',
    attr: { top: 115, left: 150, width: 300, angle: 0, scale: [1, 1], lock: false, opacity: 1, height: 72 },
    code: 'commonTitle_675b47',
    compCode: 'commonTitle',
    version: 'index',
    config: {
      link: { isBlank: false, url: '' },
      style: {
        fontFamily: 'FZLTTHJW',
        color: '#fff',
        textAlign: 'left',
        letterSpacing: 0,
        fontSize: 28,
        lineHeight: 1.5,
        textShadow: '',
        fontWeight: 'normal',
        writingMode: 'horizontal-tb',
      },
      title: '默认文本',
      groupCode: 'group_cb1409',
    },
    dataConfig: {
      autoRefresh: false,
      dataParams: [],
      dataSourceType: 0,
      fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
      frequency: 1,
      mockData: [{ content: '' }],
      specScript: '',
    },
    hided: false,
    id: 22872,
    locked: false,
    title: '',
  },
  commonTitle_0268f0: {
    alias: '普通文本',
    attr: { top: 155, left: 190, width: 300, angle: 0, scale: [1, 1], lock: false, opacity: 1, height: 72 },
    code: 'commonTitle_0268f0',
    compCode: 'commonTitle',
    version: 'index',
    config: {
      link: { isBlank: false, url: '' },
      style: {
        fontFamily: 'FZLTTHJW',
        color: '#fff',
        textAlign: 'left',
        letterSpacing: 0,
        fontSize: 28,
        lineHeight: 1.5,
        textShadow: '',
        fontWeight: 'normal',
        writingMode: 'horizontal-tb',
      },
      title: '默认文本',
    },
    dataConfig: {
      autoRefresh: false,
      dataParams: [],
      dataSourceType: 0,
      fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
      frequency: 1,
      mockData: [{ content: '' }],
      specScript: '',
    },
    hided: false,
    id: 22874,
    locked: false,
    title: '',
  },
  commonTitle_67f82d: {
    alias: '普通文本',
    attr: { top: 95, left: 130, width: 300, angle: 0, scale: [1, 1], lock: false, opacity: 1, height: 72 },
    code: 'commonTitle_67f82d',
    compCode: 'commonTitle',
    version: 'index',
    config: {
      link: { isBlank: false, url: '' },
      style: {
        fontFamily: 'FZLTTHJW',
        color: '#fff',
        textAlign: 'left',
        letterSpacing: 0,
        fontSize: 28,
        lineHeight: 1.5,
        textShadow: '',
        fontWeight: 'normal',
        writingMode: 'horizontal-tb',
      },
      title: '默认文本',
      groupCode: 'group_cb1409',
    },
    dataConfig: {
      autoRefresh: false,
      dataParams: [],
      dataSourceType: 0,
      fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
      frequency: 1,
      mockData: [{ content: '' }],
      specScript: '',
    },
    hided: false,
    id: 22871,
    locked: false,
    title: '',
  },
  commonTitle_c13c4a: {
    alias: '普通文本',
    attr: { top: 135, left: 170, width: 300, angle: 0, scale: [1, 1], lock: false, opacity: 1, height: 72 },
    code: 'commonTitle_c13c4a',
    compCode: 'commonTitle',
    version: 'index',
    config: {
      link: { isBlank: false, url: '' },
      style: {
        fontFamily: 'FZLTTHJW',
        color: '#fff',
        textAlign: 'left',
        letterSpacing: 0,
        fontSize: 28,
        lineHeight: 1.5,
        textShadow: '',
        fontWeight: 'normal',
        writingMode: 'horizontal-tb',
      },
      title: '默认文本',
    },
    dataConfig: {
      autoRefresh: false,
      dataParams: [],
      dataSourceType: 0,
      fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
      frequency: 1,
      mockData: [{ content: '' }],
      specScript: '',
    },
    hided: false,
    id: 22873,
    locked: false,
    title: '',
  },
  commonTitle_8a4743: {
    alias: '普通文本',
    attr: { top: 175, left: 210, width: 300, angle: 0, scale: [1, 1], lock: false, opacity: 1, height: 72 },
    code: 'commonTitle_8a4743',
    compCode: 'commonTitle',
    version: 'index',
    config: {
      link: { isBlank: false, url: '' },
      style: {
        fontFamily: 'FZLTTHJW',
        color: '#fff',
        textAlign: 'left',
        letterSpacing: 0,
        fontSize: 28,
        lineHeight: 1.5,
        textShadow: '',
        fontWeight: 'normal',
        writingMode: 'horizontal-tb',
      },
      title: '默认文本',
    },
    dataConfig: {
      autoRefresh: false,
      dataParams: [],
      dataSourceType: 0,
      fieldMap: [{ sourceFieldName: '', compFieldName: 'value' }],
      frequency: 1,
      mockData: [{ content: '' }],
      specScript: '',
    },
    hided: false,
    id: 22875,
    locked: false,
    title: '',
  },
  group_cb1409: {
    code: 'group_cb1409',
    version: 'index',
    compCode: 'group',
    alias: '分组',
    locked: false,
    hided: false,
    attr: { left: 90, top: 55, width: 360, height: 132, angle: 0, scale: [1, 1] },
    title: '分组',
    config: { groupItemCode: ['commonTitle_f698a3', 'commonTitle_675b47', 'commonTitle_67f82d'] },
  },
};
